---
abstract: 'Manages Gearman workers'
author:
  - 'Johannes Plunien <plu@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Slurp: 0
  File::Temp: 0
  Gearman::Server: 1.11
  Net::Telnet: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman-Driver
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Cache::FastMmap: 1.34
  DateTime: 0.4304
  Gearman::Client: 1.11
  Module::Find: 0.08
  Moose: 0.90
  MooseX::Getopt: 0.24
  MooseX::Log::Log4perl: 0.40
  MooseX::MethodAttributes: 0.18
  MooseX::Types::Path::Class: 0.05
  Net::Telnet::Gearman: 0.01000
  POE: 1.280
  Time::HiRes: 1.9715
  Try::Tiny: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.01021
